export const USER_ACTION_TYPES = {
    SET_CURRENT_USER : 'user/SET_CURRENT_USER',
    CHECK_USER_SESSION: 'user/CHECK_USER_SESSION',
    GOOGLE_SIGN_IN_START : 'user/GOOGLE_SIGN_IN_START',
    EMIAL_SIGN_IN_START : 'user/EMIAL_SIGN_IN_START',
    SIGN_IN_SUCESS: 'user/SIGN_IN_SUCESS',
    SIGN_IN_FAILURE: 'user/SIGN_IN_FAILURE',
    SIGN_UP_START: 'user/SIGN_UP_START',
    SIGN_UP_SUCESS: 'user/SIGN_UP_SUCESS',
    SIGN_UP_FAILURE: 'user/SIGN_UP_FAILURE',
    SIGN_OUT_START: 'user/SIGN_OUT_START',
    SIGN_OUT_SUCESS: 'user/SIGN_OUT_SUCESS',
    SIGN_OUT_FAILURE: 'user/SIGN_OUT_FAILURE',
    
}